language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  global:
    - CODECLIMATE_REPO_TOKEN=c46158de487f3178f23151cf4af5fbe83779d523d09fbd5f124474614be1b147
before_install: cd ./api
script:
  - npm test
install:
  - npm install
after_success:
  - npm run coverage
